// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd/gateway/grpc/protos/gateway.proto

package miniogrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Coommon / shared types
type BucketInfo struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{0}
}

func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type ObjectPartInfo struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Etag                 string   `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ActualSize           int64    `protobuf:"varint,5,opt,name=actualSize,proto3" json:"actualSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPartInfo) Reset()         { *m = ObjectPartInfo{} }
func (m *ObjectPartInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectPartInfo) ProtoMessage()    {}
func (*ObjectPartInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{1}
}

func (m *ObjectPartInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPartInfo.Unmarshal(m, b)
}
func (m *ObjectPartInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPartInfo.Marshal(b, m, deterministic)
}
func (m *ObjectPartInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPartInfo.Merge(m, src)
}
func (m *ObjectPartInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectPartInfo.Size(m)
}
func (m *ObjectPartInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPartInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPartInfo proto.InternalMessageInfo

func (m *ObjectPartInfo) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ObjectPartInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectPartInfo) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *ObjectPartInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjectPartInfo) GetActualSize() int64 {
	if m != nil {
		return m.ActualSize
	}
	return 0
}

type ObjectInfo struct {
	Bucket               string               `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=modTime,proto3" json:"modTime,omitempty"`
	Size                 int64                `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsDir                bool                 `protobuf:"varint,5,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Etag                 string               `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	ContentType          string               `protobuf:"bytes,7,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,8,opt,name=expires,proto3" json:"expires,omitempty"`
	StorageClass         string               `protobuf:"bytes,9,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	UserDefined          map[string]string    `protobuf:"bytes,10,rep,name=userDefined,proto3" json:"userDefined,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Parts                []*ObjectPartInfo    `protobuf:"bytes,11,rep,name=parts,proto3" json:"parts,omitempty"`
	AccTime              *timestamp.Timestamp `protobuf:"bytes,12,opt,name=accTime,proto3" json:"accTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{2}
}

func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectInfo) GetModTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModTime
	}
	return nil
}

func (m *ObjectInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjectInfo) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *ObjectInfo) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *ObjectInfo) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *ObjectInfo) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *ObjectInfo) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

func (m *ObjectInfo) GetUserDefined() map[string]string {
	if m != nil {
		return m.UserDefined
	}
	return nil
}

func (m *ObjectInfo) GetParts() []*ObjectPartInfo {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *ObjectInfo) GetAccTime() *timestamp.Timestamp {
	if m != nil {
		return m.AccTime
	}
	return nil
}

type RangeSpec struct {
	IsSuffixLength       bool     `protobuf:"varint,1,opt,name=isSuffixLength,proto3" json:"isSuffixLength,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeSpec) Reset()         { *m = RangeSpec{} }
func (m *RangeSpec) String() string { return proto.CompactTextString(m) }
func (*RangeSpec) ProtoMessage()    {}
func (*RangeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{3}
}

func (m *RangeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeSpec.Unmarshal(m, b)
}
func (m *RangeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeSpec.Marshal(b, m, deterministic)
}
func (m *RangeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeSpec.Merge(m, src)
}
func (m *RangeSpec) XXX_Size() int {
	return xxx_messageInfo_RangeSpec.Size(m)
}
func (m *RangeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_RangeSpec proto.InternalMessageInfo

func (m *RangeSpec) GetIsSuffixLength() bool {
	if m != nil {
		return m.IsSuffixLength
	}
	return false
}

func (m *RangeSpec) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *RangeSpec) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type HeaderValues struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderValues) Reset()         { *m = HeaderValues{} }
func (m *HeaderValues) String() string { return proto.CompactTextString(m) }
func (*HeaderValues) ProtoMessage()    {}
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{4}
}

func (m *HeaderValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderValues.Unmarshal(m, b)
}
func (m *HeaderValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderValues.Marshal(b, m, deterministic)
}
func (m *HeaderValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderValues.Merge(m, src)
}
func (m *HeaderValues) XXX_Size() int {
	return xxx_messageInfo_HeaderValues.Size(m)
}
func (m *HeaderValues) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderValues.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderValues proto.InternalMessageInfo

func (m *HeaderValues) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Headers struct {
	Keys                 map[string]*HeaderValues `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Headers) Reset()         { *m = Headers{} }
func (m *Headers) String() string { return proto.CompactTextString(m) }
func (*Headers) ProtoMessage()    {}
func (*Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{5}
}

func (m *Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Headers.Unmarshal(m, b)
}
func (m *Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Headers.Marshal(b, m, deterministic)
}
func (m *Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Headers.Merge(m, src)
}
func (m *Headers) XXX_Size() int {
	return xxx_messageInfo_Headers.Size(m)
}
func (m *Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Headers proto.InternalMessageInfo

func (m *Headers) GetKeys() map[string]*HeaderValues {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ObjectOptions struct {
	// TOOD(cmaloney): ServerSide encryption messaging.
	UserDefined          map[string]string `protobuf:"bytes,2,rep,name=userDefined,proto3" json:"userDefined,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectOptions) Reset()         { *m = ObjectOptions{} }
func (m *ObjectOptions) String() string { return proto.CompactTextString(m) }
func (*ObjectOptions) ProtoMessage()    {}
func (*ObjectOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{6}
}

func (m *ObjectOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectOptions.Unmarshal(m, b)
}
func (m *ObjectOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectOptions.Marshal(b, m, deterministic)
}
func (m *ObjectOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectOptions.Merge(m, src)
}
func (m *ObjectOptions) XXX_Size() int {
	return xxx_messageInfo_ObjectOptions.Size(m)
}
func (m *ObjectOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectOptions proto.InternalMessageInfo

func (m *ObjectOptions) GetUserDefined() map[string]string {
	if m != nil {
		return m.UserDefined
	}
	return nil
}

// Individual request/response type pairs
type ShutdownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{7}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

type ShutdownResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{8}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

func (m *ShutdownResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetBucketInfoRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketInfoRequest) Reset()         { *m = GetBucketInfoRequest{} }
func (m *GetBucketInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetBucketInfoRequest) ProtoMessage()    {}
func (*GetBucketInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{9}
}

func (m *GetBucketInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketInfoRequest.Unmarshal(m, b)
}
func (m *GetBucketInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetBucketInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketInfoRequest.Merge(m, src)
}
func (m *GetBucketInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetBucketInfoRequest.Size(m)
}
func (m *GetBucketInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketInfoRequest proto.InternalMessageInfo

func (m *GetBucketInfoRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type GetBucketInfoResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *BucketInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBucketInfoResponse) Reset()         { *m = GetBucketInfoResponse{} }
func (m *GetBucketInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetBucketInfoResponse) ProtoMessage()    {}
func (*GetBucketInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{10}
}

func (m *GetBucketInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketInfoResponse.Unmarshal(m, b)
}
func (m *GetBucketInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetBucketInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketInfoResponse.Merge(m, src)
}
func (m *GetBucketInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetBucketInfoResponse.Size(m)
}
func (m *GetBucketInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketInfoResponse proto.InternalMessageInfo

func (m *GetBucketInfoResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetBucketInfoResponse) GetInfo() *BucketInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ListBucketsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBucketsRequest) Reset()         { *m = ListBucketsRequest{} }
func (m *ListBucketsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBucketsRequest) ProtoMessage()    {}
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{11}
}

func (m *ListBucketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketsRequest.Unmarshal(m, b)
}
func (m *ListBucketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketsRequest.Marshal(b, m, deterministic)
}
func (m *ListBucketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketsRequest.Merge(m, src)
}
func (m *ListBucketsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBucketsRequest.Size(m)
}
func (m *ListBucketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketsRequest proto.InternalMessageInfo

type ListBucketsResponse struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 []*BucketInfo `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBucketsResponse) Reset()         { *m = ListBucketsResponse{} }
func (m *ListBucketsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBucketsResponse) ProtoMessage()    {}
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{12}
}

func (m *ListBucketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketsResponse.Unmarshal(m, b)
}
func (m *ListBucketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketsResponse.Marshal(b, m, deterministic)
}
func (m *ListBucketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketsResponse.Merge(m, src)
}
func (m *ListBucketsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBucketsResponse.Size(m)
}
func (m *ListBucketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketsResponse proto.InternalMessageInfo

func (m *ListBucketsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListBucketsResponse) GetInfo() []*BucketInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ListObjectsRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Marker               string   `protobuf:"bytes,3,opt,name=marker,proto3" json:"marker,omitempty"`
	Delimiter            string   `protobuf:"bytes,4,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	MaxKeys              int64    `protobuf:"varint,5,opt,name=maxKeys,proto3" json:"maxKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListObjectsRequest) Reset()         { *m = ListObjectsRequest{} }
func (m *ListObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListObjectsRequest) ProtoMessage()    {}
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{13}
}

func (m *ListObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsRequest.Unmarshal(m, b)
}
func (m *ListObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsRequest.Merge(m, src)
}
func (m *ListObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListObjectsRequest.Size(m)
}
func (m *ListObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsRequest proto.InternalMessageInfo

func (m *ListObjectsRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ListObjectsRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *ListObjectsRequest) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *ListObjectsRequest) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func (m *ListObjectsRequest) GetMaxKeys() int64 {
	if m != nil {
		return m.MaxKeys
	}
	return 0
}

type ListObjectsResponse struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsTruncated          bool          `protobuf:"varint,2,opt,name=isTruncated,proto3" json:"isTruncated,omitempty"`
	NextMarker           string        `protobuf:"bytes,3,opt,name=nextMarker,proto3" json:"nextMarker,omitempty"`
	Objects              []*ObjectInfo `protobuf:"bytes,4,rep,name=objects,proto3" json:"objects,omitempty"`
	Prefixes             []string      `protobuf:"bytes,5,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListObjectsResponse) Reset()         { *m = ListObjectsResponse{} }
func (m *ListObjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListObjectsResponse) ProtoMessage()    {}
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{14}
}

func (m *ListObjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsResponse.Unmarshal(m, b)
}
func (m *ListObjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListObjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsResponse.Merge(m, src)
}
func (m *ListObjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListObjectsResponse.Size(m)
}
func (m *ListObjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsResponse proto.InternalMessageInfo

func (m *ListObjectsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListObjectsResponse) GetIsTruncated() bool {
	if m != nil {
		return m.IsTruncated
	}
	return false
}

func (m *ListObjectsResponse) GetNextMarker() string {
	if m != nil {
		return m.NextMarker
	}
	return ""
}

func (m *ListObjectsResponse) GetObjects() []*ObjectInfo {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *ListObjectsResponse) GetPrefixes() []string {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

type ListObjectsV2Request struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ContinuationToken    string   `protobuf:"bytes,3,opt,name=continuationToken,proto3" json:"continuationToken,omitempty"`
	Delimiter            string   `protobuf:"bytes,4,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	MaxKeys              int64    `protobuf:"varint,5,opt,name=maxKeys,proto3" json:"maxKeys,omitempty"`
	FetchOwner           bool     `protobuf:"varint,6,opt,name=fetchOwner,proto3" json:"fetchOwner,omitempty"`
	StartAfter           string   `protobuf:"bytes,7,opt,name=startAfter,proto3" json:"startAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListObjectsV2Request) Reset()         { *m = ListObjectsV2Request{} }
func (m *ListObjectsV2Request) String() string { return proto.CompactTextString(m) }
func (*ListObjectsV2Request) ProtoMessage()    {}
func (*ListObjectsV2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{15}
}

func (m *ListObjectsV2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsV2Request.Unmarshal(m, b)
}
func (m *ListObjectsV2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsV2Request.Marshal(b, m, deterministic)
}
func (m *ListObjectsV2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsV2Request.Merge(m, src)
}
func (m *ListObjectsV2Request) XXX_Size() int {
	return xxx_messageInfo_ListObjectsV2Request.Size(m)
}
func (m *ListObjectsV2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsV2Request.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsV2Request proto.InternalMessageInfo

func (m *ListObjectsV2Request) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ListObjectsV2Request) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *ListObjectsV2Request) GetContinuationToken() string {
	if m != nil {
		return m.ContinuationToken
	}
	return ""
}

func (m *ListObjectsV2Request) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func (m *ListObjectsV2Request) GetMaxKeys() int64 {
	if m != nil {
		return m.MaxKeys
	}
	return 0
}

func (m *ListObjectsV2Request) GetFetchOwner() bool {
	if m != nil {
		return m.FetchOwner
	}
	return false
}

func (m *ListObjectsV2Request) GetStartAfter() string {
	if m != nil {
		return m.StartAfter
	}
	return ""
}

type ListObjectsV2Response struct {
	IsTruncated           bool          `protobuf:"varint,1,opt,name=isTruncated,proto3" json:"isTruncated,omitempty"`
	ContinuationToken     string        `protobuf:"bytes,2,opt,name=continuationToken,proto3" json:"continuationToken,omitempty"`
	NextContinuationToken string        `protobuf:"bytes,3,opt,name=nextContinuationToken,proto3" json:"nextContinuationToken,omitempty"`
	Objects               []*ObjectInfo `protobuf:"bytes,4,rep,name=objects,proto3" json:"objects,omitempty"`
	Prefixes              []string      `protobuf:"bytes,5,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *ListObjectsV2Response) Reset()         { *m = ListObjectsV2Response{} }
func (m *ListObjectsV2Response) String() string { return proto.CompactTextString(m) }
func (*ListObjectsV2Response) ProtoMessage()    {}
func (*ListObjectsV2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{16}
}

func (m *ListObjectsV2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsV2Response.Unmarshal(m, b)
}
func (m *ListObjectsV2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsV2Response.Marshal(b, m, deterministic)
}
func (m *ListObjectsV2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsV2Response.Merge(m, src)
}
func (m *ListObjectsV2Response) XXX_Size() int {
	return xxx_messageInfo_ListObjectsV2Response.Size(m)
}
func (m *ListObjectsV2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsV2Response.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsV2Response proto.InternalMessageInfo

func (m *ListObjectsV2Response) GetIsTruncated() bool {
	if m != nil {
		return m.IsTruncated
	}
	return false
}

func (m *ListObjectsV2Response) GetContinuationToken() string {
	if m != nil {
		return m.ContinuationToken
	}
	return ""
}

func (m *ListObjectsV2Response) GetNextContinuationToken() string {
	if m != nil {
		return m.NextContinuationToken
	}
	return ""
}

func (m *ListObjectsV2Response) GetObjects() []*ObjectInfo {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *ListObjectsV2Response) GetPrefixes() []string {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

type GetObjectNInfoRequest struct {
	Bucket               string         `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object               string         `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	RangeSpec            *RangeSpec     `protobuf:"bytes,3,opt,name=rangeSpec,proto3" json:"rangeSpec,omitempty"`
	Headers              *Headers       `protobuf:"bytes,4,opt,name=headers,proto3" json:"headers,omitempty"`
	LockType             int64          `protobuf:"varint,5,opt,name=lockType,proto3" json:"lockType,omitempty"`
	Options              *ObjectOptions `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetObjectNInfoRequest) Reset()         { *m = GetObjectNInfoRequest{} }
func (m *GetObjectNInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectNInfoRequest) ProtoMessage()    {}
func (*GetObjectNInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{17}
}

func (m *GetObjectNInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectNInfoRequest.Unmarshal(m, b)
}
func (m *GetObjectNInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectNInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectNInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectNInfoRequest.Merge(m, src)
}
func (m *GetObjectNInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectNInfoRequest.Size(m)
}
func (m *GetObjectNInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectNInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectNInfoRequest proto.InternalMessageInfo

func (m *GetObjectNInfoRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetObjectNInfoRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *GetObjectNInfoRequest) GetRangeSpec() *RangeSpec {
	if m != nil {
		return m.RangeSpec
	}
	return nil
}

func (m *GetObjectNInfoRequest) GetHeaders() *Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *GetObjectNInfoRequest) GetLockType() int64 {
	if m != nil {
		return m.LockType
	}
	return 0
}

func (m *GetObjectNInfoRequest) GetOptions() *ObjectOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type GetObjectNInfoResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ObjectInfo           *ObjectInfo `protobuf:"bytes,2,opt,name=objectInfo,proto3" json:"objectInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetObjectNInfoResponse) Reset()         { *m = GetObjectNInfoResponse{} }
func (m *GetObjectNInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectNInfoResponse) ProtoMessage()    {}
func (*GetObjectNInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{18}
}

func (m *GetObjectNInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectNInfoResponse.Unmarshal(m, b)
}
func (m *GetObjectNInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectNInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectNInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectNInfoResponse.Merge(m, src)
}
func (m *GetObjectNInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectNInfoResponse.Size(m)
}
func (m *GetObjectNInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectNInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectNInfoResponse proto.InternalMessageInfo

func (m *GetObjectNInfoResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetObjectNInfoResponse) GetObjectInfo() *ObjectInfo {
	if m != nil {
		return m.ObjectInfo
	}
	return nil
}

type GetObjectRequest struct {
	Bucket      string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object      string `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	StartOffset int64  `protobuf:"varint,3,opt,name=startOffset,proto3" json:"startOffset,omitempty"`
	EndOffset   int64  `protobuf:"varint,4,opt,name=endOffset,proto3" json:"endOffset,omitempty"`
	// TODO(cmaloney): Writer
	Etag                 string         `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	Options              *ObjectOptions `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{19}
}

func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(m, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetObjectRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *GetObjectRequest) GetStartOffset() int64 {
	if m != nil {
		return m.StartOffset
	}
	return 0
}

func (m *GetObjectRequest) GetEndOffset() int64 {
	if m != nil {
		return m.EndOffset
	}
	return 0
}

func (m *GetObjectRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *GetObjectRequest) GetOptions() *ObjectOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type GetObjectResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponse) Reset()         { *m = GetObjectResponse{} }
func (m *GetObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse) ProtoMessage()    {}
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{20}
}

func (m *GetObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse.Unmarshal(m, b)
}
func (m *GetObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse.Merge(m, src)
}
func (m *GetObjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse.Size(m)
}
func (m *GetObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse proto.InternalMessageInfo

func (m *GetObjectResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetObjectInfoRequest struct {
	Bucket               string         `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object               string         `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Options              *ObjectOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetObjectInfoRequest) Reset()         { *m = GetObjectInfoRequest{} }
func (m *GetObjectInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectInfoRequest) ProtoMessage()    {}
func (*GetObjectInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{21}
}

func (m *GetObjectInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectInfoRequest.Unmarshal(m, b)
}
func (m *GetObjectInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectInfoRequest.Merge(m, src)
}
func (m *GetObjectInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectInfoRequest.Size(m)
}
func (m *GetObjectInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectInfoRequest proto.InternalMessageInfo

func (m *GetObjectInfoRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetObjectInfoRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *GetObjectInfoRequest) GetOptions() *ObjectOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type GetObjectInfoResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *ObjectInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetObjectInfoResponse) Reset()         { *m = GetObjectInfoResponse{} }
func (m *GetObjectInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectInfoResponse) ProtoMessage()    {}
func (*GetObjectInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4eb9e85e67b90c02, []int{22}
}

func (m *GetObjectInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectInfoResponse.Unmarshal(m, b)
}
func (m *GetObjectInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectInfoResponse.Merge(m, src)
}
func (m *GetObjectInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectInfoResponse.Size(m)
}
func (m *GetObjectInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectInfoResponse proto.InternalMessageInfo

func (m *GetObjectInfoResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetObjectInfoResponse) GetInfo() *ObjectInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*BucketInfo)(nil), "miniogrpc.BucketInfo")
	proto.RegisterType((*ObjectPartInfo)(nil), "miniogrpc.ObjectPartInfo")
	proto.RegisterType((*ObjectInfo)(nil), "miniogrpc.ObjectInfo")
	proto.RegisterMapType((map[string]string)(nil), "miniogrpc.ObjectInfo.UserDefinedEntry")
	proto.RegisterType((*RangeSpec)(nil), "miniogrpc.RangeSpec")
	proto.RegisterType((*HeaderValues)(nil), "miniogrpc.HeaderValues")
	proto.RegisterType((*Headers)(nil), "miniogrpc.Headers")
	proto.RegisterMapType((map[string]*HeaderValues)(nil), "miniogrpc.Headers.KeysEntry")
	proto.RegisterType((*ObjectOptions)(nil), "miniogrpc.ObjectOptions")
	proto.RegisterMapType((map[string]string)(nil), "miniogrpc.ObjectOptions.UserDefinedEntry")
	proto.RegisterType((*ShutdownRequest)(nil), "miniogrpc.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "miniogrpc.ShutdownResponse")
	proto.RegisterType((*GetBucketInfoRequest)(nil), "miniogrpc.GetBucketInfoRequest")
	proto.RegisterType((*GetBucketInfoResponse)(nil), "miniogrpc.GetBucketInfoResponse")
	proto.RegisterType((*ListBucketsRequest)(nil), "miniogrpc.ListBucketsRequest")
	proto.RegisterType((*ListBucketsResponse)(nil), "miniogrpc.ListBucketsResponse")
	proto.RegisterType((*ListObjectsRequest)(nil), "miniogrpc.ListObjectsRequest")
	proto.RegisterType((*ListObjectsResponse)(nil), "miniogrpc.ListObjectsResponse")
	proto.RegisterType((*ListObjectsV2Request)(nil), "miniogrpc.ListObjectsV2Request")
	proto.RegisterType((*ListObjectsV2Response)(nil), "miniogrpc.ListObjectsV2Response")
	proto.RegisterType((*GetObjectNInfoRequest)(nil), "miniogrpc.GetObjectNInfoRequest")
	proto.RegisterType((*GetObjectNInfoResponse)(nil), "miniogrpc.GetObjectNInfoResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "miniogrpc.GetObjectRequest")
	proto.RegisterType((*GetObjectResponse)(nil), "miniogrpc.GetObjectResponse")
	proto.RegisterType((*GetObjectInfoRequest)(nil), "miniogrpc.GetObjectInfoRequest")
	proto.RegisterType((*GetObjectInfoResponse)(nil), "miniogrpc.GetObjectInfoResponse")
}

func init() {
	proto.RegisterFile("cmd/gateway/grpc/protos/gateway.proto", fileDescriptor_4eb9e85e67b90c02)
}

var fileDescriptor_4eb9e85e67b90c02 = []byte{
	// 1223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x0e, 0x2d, 0xc9, 0x92, 0x86, 0x4e, 0x5e, 0x7b, 0x5f, 0x3b, 0x65, 0x19, 0x37, 0x56, 0x89,
	0xd6, 0xb0, 0x81, 0x54, 0x2a, 0x58, 0x17, 0x28, 0x0a, 0x34, 0x40, 0x9b, 0x04, 0x71, 0x90, 0x0f,
	0x07, 0xb4, 0xeb, 0x1e, 0x7a, 0xa2, 0xa9, 0xa5, 0xcc, 0x4a, 0x5c, 0xaa, 0xdc, 0x65, 0x6d, 0xf9,
	0xdc, 0x6b, 0x6f, 0xbd, 0xb4, 0xe8, 0x2f, 0xea, 0xa5, 0xff, 0xa3, 0xe8, 0x1f, 0xe8, 0xad, 0xd8,
	0x0f, 0x52, 0x2b, 0x91, 0xb2, 0x63, 0x27, 0x37, 0xce, 0xcc, 0xb3, 0xcf, 0xce, 0x97, 0x66, 0x56,
	0xf0, 0x71, 0x10, 0xf7, 0x7b, 0x03, 0x9f, 0xe1, 0x33, 0x7f, 0xd2, 0x1b, 0xa4, 0xe3, 0xa0, 0x37,
	0x4e, 0x13, 0x96, 0xd0, 0x5c, 0xd7, 0x15, 0x22, 0x6a, 0xc7, 0x11, 0x89, 0x12, 0x6e, 0xb7, 0x3f,
	0x5a, 0x74, 0x82, 0x32, 0x9f, 0x65, 0x54, 0x1e, 0xb0, 0xb7, 0x06, 0x49, 0x32, 0x18, 0x61, 0x69,
	0x3b, 0xc9, 0xc2, 0x1e, 0x8b, 0x62, 0x4c, 0x99, 0x1f, 0x8f, 0x25, 0xc0, 0x39, 0x06, 0xf8, 0x26,
	0x0b, 0x86, 0x98, 0x3d, 0x23, 0x61, 0x82, 0x10, 0xd4, 0x89, 0x1f, 0x63, 0xcb, 0xe8, 0x18, 0x3b,
	0x6d, 0x4f, 0x7c, 0xa3, 0x3d, 0x68, 0x06, 0x29, 0xf6, 0x19, 0xee, 0x5b, 0x4b, 0x1d, 0x63, 0xc7,
	0x74, 0xed, 0xae, 0x24, 0xed, 0xe6, 0xa4, 0xdd, 0xa3, 0x9c, 0xd4, 0xcb, 0xa1, 0xce, 0xcf, 0x06,
	0xdc, 0x39, 0x38, 0xf9, 0x01, 0x07, 0xec, 0xb5, 0x9f, 0x4a, 0xf2, 0xbb, 0xb0, 0x4c, 0xb2, 0xf8,
	0x04, 0xa7, 0x82, 0xbe, 0xe1, 0x29, 0xa9, 0xb8, 0x74, 0x49, 0xbb, 0x14, 0x41, 0x1d, 0x33, 0x7f,
	0x60, 0xd5, 0xa4, 0x8e, 0x7f, 0x73, 0x1d, 0x8d, 0x2e, 0xb0, 0x55, 0xef, 0x18, 0x3b, 0x35, 0x4f,
	0x7c, 0xa3, 0xfb, 0x00, 0x7e, 0xc0, 0x32, 0x7f, 0x74, 0xc8, 0x2d, 0x0d, 0x61, 0xd1, 0x34, 0xce,
	0x6f, 0x75, 0x00, 0xe9, 0x46, 0xee, 0xc2, 0x89, 0x88, 0x56, 0x45, 0xa8, 0xa4, 0x4a, 0x17, 0xf6,
	0xa0, 0x19, 0x27, 0x7d, 0x1e, 0x9a, 0xf0, 0xe2, 0x8a, 0xb8, 0x15, 0xb4, 0xd2, 0xc9, 0x75, 0x68,
	0x44, 0xf4, 0x71, 0x94, 0x0a, 0xff, 0x5a, 0x9e, 0x14, 0x8a, 0x10, 0x97, 0xb5, 0x10, 0x3b, 0x60,
	0x06, 0x09, 0x61, 0x98, 0xb0, 0xa3, 0xc9, 0x18, 0x5b, 0x4d, 0x61, 0xd2, 0x55, 0xdc, 0x2b, 0x7c,
	0x3e, 0x8e, 0x52, 0x4c, 0xad, 0xd6, 0xd5, 0x5e, 0x29, 0x28, 0x72, 0x60, 0x85, 0xb2, 0x24, 0xf5,
	0x07, 0xf8, 0xd1, 0xc8, 0xa7, 0xd4, 0x6a, 0x0b, 0xe2, 0x19, 0x1d, 0xda, 0x07, 0x33, 0xa3, 0x38,
	0x7d, 0x8c, 0xc3, 0x88, 0xe0, 0xbe, 0x05, 0x9d, 0xda, 0x8e, 0xe9, 0x6e, 0x77, 0x8b, 0x8e, 0xeb,
	0x4e, 0xf3, 0xd8, 0xfd, 0x76, 0x0a, 0x7c, 0x42, 0x58, 0x3a, 0xf1, 0xf4, 0xa3, 0xa8, 0x07, 0x8d,
	0xb1, 0x9f, 0x32, 0x6a, 0x99, 0x82, 0xe3, 0xfd, 0x12, 0x47, 0xde, 0x12, 0x9e, 0xc4, 0xf1, 0xa0,
	0xfc, 0x20, 0x10, 0xa9, 0x5e, 0xb9, 0x3a, 0x28, 0x05, 0xb5, 0x1f, 0xc2, 0xea, 0xbc, 0x1f, 0x68,
	0x15, 0x6a, 0x43, 0x3c, 0x51, 0xd5, 0xe5, 0x9f, 0x3c, 0xf9, 0x3f, 0xf9, 0xa3, 0x2c, 0xaf, 0xad,
	0x14, 0xbe, 0x5c, 0xfa, 0xc2, 0x70, 0xbe, 0x87, 0xb6, 0xe7, 0x93, 0x01, 0x3e, 0x1c, 0xe3, 0x00,
	0x6d, 0xc3, 0x9d, 0x88, 0x1e, 0x66, 0x61, 0x18, 0x9d, 0xbf, 0xc0, 0x64, 0xc0, 0x4e, 0x05, 0x47,
	0xcb, 0x9b, 0xd3, 0x72, 0x3a, 0xca, 0xfc, 0x94, 0x09, 0xba, 0x9a, 0x27, 0x05, 0x7e, 0x2d, 0x26,
	0x7d, 0xd1, 0x27, 0x35, 0x8f, 0x7f, 0x3a, 0xdb, 0xb0, 0xb2, 0x8f, 0xfd, 0x3e, 0x4e, 0x8f, 0xf9,
	0x7d, 0x94, 0x77, 0x9e, 0xb8, 0x99, 0x5a, 0x46, 0xa7, 0xc6, 0x3b, 0x4f, 0x4a, 0xce, 0x2f, 0x06,
	0x34, 0x25, 0x90, 0xa2, 0x4f, 0xa1, 0x3e, 0xc4, 0x13, 0x89, 0x30, 0xdd, 0x4d, 0x2d, 0x6d, 0x0a,
	0xd1, 0x7d, 0x8e, 0x27, 0x54, 0x26, 0x5c, 0x20, 0xed, 0xd7, 0xd0, 0x2e, 0x54, 0x15, 0xb1, 0x7f,
	0xa2, 0xc7, 0x6e, 0xba, 0xef, 0x95, 0x18, 0xa5, 0x73, 0x7a, 0x52, 0xfe, 0x30, 0xe0, 0xb6, 0x2c,
	0xd2, 0xc1, 0x98, 0x45, 0x09, 0xa1, 0xe8, 0xf9, 0x6c, 0x5f, 0x2c, 0x09, 0xe7, 0x76, 0x4b, 0x35,
	0x55, 0xf0, 0xcb, 0x5b, 0xe3, 0xad, 0x6b, 0xb6, 0x06, 0xff, 0x3b, 0x3c, 0xcd, 0x58, 0x3f, 0x39,
	0x23, 0x1e, 0xfe, 0x31, 0xc3, 0x94, 0x39, 0x5f, 0xc1, 0xea, 0x54, 0x45, 0xc7, 0x09, 0xa1, 0x18,
	0xed, 0xc2, 0xb2, 0x1c, 0x83, 0x82, 0xd5, 0x74, 0xd7, 0x34, 0x77, 0x0f, 0x85, 0xc1, 0x53, 0x00,
	0xa7, 0x0b, 0xeb, 0x4f, 0x31, 0x9b, 0xce, 0x40, 0x45, 0xbb, 0x68, 0x54, 0x38, 0x31, 0x6c, 0xcc,
	0xe1, 0xaf, 0x7d, 0x27, 0xda, 0x85, 0x7a, 0x44, 0xc2, 0x44, 0x95, 0x65, 0x43, 0x03, 0x6a, 0xbc,
	0x02, 0xe2, 0xac, 0x03, 0x7a, 0x11, 0x51, 0x75, 0x1f, 0xcd, 0x63, 0x1e, 0xc2, 0xff, 0x67, 0xb4,
	0x6f, 0xe3, 0x42, 0xed, 0x2a, 0x17, 0x7e, 0x35, 0xa4, 0x0f, 0xb2, 0xce, 0xf4, 0x8a, 0x04, 0x71,
	0xfd, 0x38, 0xc5, 0x61, 0x74, 0xae, 0xaa, 0xa7, 0x24, 0xae, 0x8f, 0xfd, 0x74, 0x88, 0x53, 0x35,
	0xd4, 0x95, 0x84, 0x36, 0xa1, 0xdd, 0xc7, 0xa3, 0x28, 0x8e, 0x18, 0x4e, 0xc5, 0xd8, 0x6c, 0x7b,
	0x53, 0x05, 0xb2, 0xa0, 0x19, 0xfb, 0xe7, 0xbc, 0xc9, 0xd5, 0x74, 0xcf, 0x45, 0xe7, 0x2f, 0x43,
	0x26, 0xa1, 0x70, 0xeb, 0xfa, 0x49, 0xe8, 0x80, 0x19, 0xd1, 0xa3, 0x34, 0x23, 0x41, 0xb1, 0xde,
	0x5a, 0x9e, 0xae, 0xe2, 0xfb, 0x85, 0xe0, 0x73, 0xf6, 0x52, 0x77, 0x5c, 0xd3, 0xa0, 0x1e, 0x34,
	0x13, 0x79, 0xbf, 0x55, 0x2f, 0x65, 0x72, 0x3a, 0x30, 0xbd, 0x1c, 0x85, 0x6c, 0x68, 0xc9, 0x7c,
	0x60, 0x1e, 0x10, 0x9f, 0x04, 0x85, 0xec, 0xfc, 0x63, 0xc0, 0xba, 0x16, 0xd1, 0xb1, 0x7b, 0xd3,
	0x54, 0x3f, 0x80, 0x35, 0xbe, 0x33, 0x22, 0x92, 0xf9, 0xfc, 0x47, 0x79, 0x94, 0x0c, 0x31, 0x51,
	0xce, 0x97, 0x0d, 0x37, 0x2d, 0x00, 0xcf, 0x4d, 0x88, 0x59, 0x70, 0x7a, 0x70, 0x46, 0x70, 0x2a,
	0xd6, 0x58, 0xcb, 0xd3, 0x34, 0xdc, 0x2e, 0xa6, 0xe3, 0xd7, 0x21, 0x27, 0x96, 0xbb, 0x4c, 0xd3,
	0x38, 0x7f, 0x1b, 0xb0, 0x31, 0x17, 0xae, 0x2a, 0xe1, 0x5c, 0x5d, 0x8c, 0x72, 0x5d, 0x2a, 0x23,
	0x5c, 0x5a, 0x14, 0xe1, 0x1e, 0x6c, 0xf0, 0x9a, 0x3d, 0x5a, 0x90, 0x93, 0x6a, 0xe3, 0xbb, 0xad,
	0xed, 0xbf, 0x86, 0x98, 0x1b, 0xf2, 0xd8, 0xab, 0x37, 0x18, 0x34, 0x5c, 0x2f, 0x89, 0xf3, 0xe2,
	0x4a, 0x09, 0xb9, 0xd0, 0x4e, 0xf3, 0xb5, 0xa5, 0x5e, 0x26, 0xeb, 0x9a, 0x63, 0xc5, 0x4a, 0xf3,
	0xa6, 0x30, 0xf4, 0x00, 0x9a, 0xa7, 0x72, 0x85, 0x88, 0x02, 0x9b, 0x2e, 0x2a, 0x2f, 0x17, 0x2f,
	0x87, 0xf0, 0x38, 0x46, 0x49, 0x30, 0x14, 0x4f, 0x10, 0x59, 0xf3, 0x42, 0x46, 0x2e, 0x34, 0x13,
	0x39, 0xe9, 0x45, 0xc5, 0x4d, 0xd7, 0x5a, 0xb4, 0x09, 0xbc, 0x1c, 0xe8, 0x5c, 0xc0, 0xdd, 0xf9,
	0xd0, 0xaf, 0xff, 0x5b, 0xfd, 0x1c, 0x20, 0x29, 0x72, 0x5e, 0x31, 0x39, 0xb5, 0x82, 0x68, 0x40,
	0xe7, 0x4f, 0x03, 0x56, 0x8b, 0xcb, 0x6f, 0x9a, 0xf2, 0x0e, 0x98, 0xa2, 0x6f, 0x0f, 0xc2, 0x90,
	0x62, 0xa6, 0xd6, 0xbc, 0xae, 0xe2, 0xbf, 0x21, 0x4c, 0xfa, 0xca, 0x2e, 0xdf, 0x7e, 0x53, 0x45,
	0xf1, 0xd4, 0x6b, 0x68, 0x4f, 0xbd, 0x9b, 0x24, 0xf2, 0x21, 0xac, 0x69, 0xb1, 0x5c, 0x7f, 0xd7,
	0x5d, 0x88, 0x5d, 0xa7, 0x65, 0xea, 0xc6, 0x2d, 0x58, 0xf8, 0x5e, 0x7b, 0x53, 0xdf, 0x63, 0xad,
	0xff, 0xdf, 0xfd, 0xde, 0xd4, 0x78, 0x05, 0xc4, 0xfd, 0xbd, 0x01, 0x2b, 0x2f, 0x23, 0xf2, 0xec,
	0xe0, 0xa9, 0xfc, 0x8b, 0x84, 0x9e, 0x40, 0x2b, 0x7f, 0x26, 0x20, 0x5b, 0xbf, 0x62, 0xf6, 0x39,
	0x61, 0xdf, 0xab, 0xb4, 0x49, 0x5f, 0x9d, 0x5b, 0xe8, 0x08, 0x6e, 0xcf, 0xac, 0x7f, 0xb4, 0xa5,
	0xe1, 0xab, 0x1e, 0x12, 0x76, 0x67, 0x31, 0xa0, 0x60, 0x7d, 0x05, 0xa6, 0xb6, 0xcf, 0xd1, 0x07,
	0xda, 0x91, 0xf2, 0xf6, 0xb7, 0xef, 0x2f, 0x32, 0xcf, 0xf3, 0xa9, 0xc9, 0x5a, 0xe2, 0x9b, 0xdd,
	0xe4, 0x25, 0xbe, 0xb9, 0x8d, 0x2a, 0xa3, 0x9e, 0x99, 0xd4, 0x33, 0x51, 0x57, 0xad, 0xac, 0x99,
	0xa8, 0x2b, 0x87, 0xbc, 0x73, 0x0b, 0x7d, 0x07, 0x77, 0x66, 0xe7, 0x02, 0x9a, 0xcb, 0x55, 0x79,
	0x5a, 0xda, 0x1f, 0x5e, 0x82, 0x28, 0x88, 0xf7, 0xa1, 0x5d, 0xd8, 0xd0, 0xbd, 0xaa, 0x13, 0x39,
	0xdd, 0x66, 0xb5, 0x71, 0xae, 0xdc, 0xda, 0x3f, 0xc8, 0xad, 0xaa, 0x03, 0x97, 0x94, 0xbb, 0xdc,
	0xf0, 0xce, 0xad, 0x93, 0x65, 0xf1, 0xb7, 0xe6, 0xb3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd2,
	0x5c, 0x56, 0x4f, 0xf6, 0x0f, 0x00, 0x00,
}
